define([
    "./animates",
    "./browser",
    "./css",
    "./data",
    "./eventer",
    "./finder",
    "./fx",
    "./geom",
    "./iframes",
    "./lists",
    "./noder",
    "./query",
    "./styler",
    "./transforms",
    "./transits",
    "./velm"
], function(browser,css,data,eventer,finder,fx,geom,iframes,lists,noder,query,styler,transforms,velm) {
    return {
        animates,
        browser,
        css,
        data,
        eventer,
        finder,
        geom,
        lists,
        noder,
        iframes,
        query,
        styler,
        transforms,
        transits,
        velm
    };
})
